### PR TITLE
fix(dunning): Clear fields when sales_invoice is empty

### PR DESCRIPTION
**Pull request by creamdory**
https://github.com/newmatik/dunning/issues/12

**IMAGE REMOVED DUE TO PRIVACY CONCERNS**

### CODE REVIEW

**Comment by KanchanChauhan** [comment]
@creamdory We don't have to do all this. Actually calculate_overdue_days is triggered because of posting date, nothing else get set.  Just need check if `frm.doc.posting_date && frm.doc.due_date` only then calculate overdue_days.

**Comment by creamdory** [comment]
@KanchanChauhan tried your suggestion. It is caching the fields and not clearing fields when `Sales Invoice` is emptied. Same is true when duplicatin a dunning and just changing the `Sales Invoice`.

**IMAGE REMOVED DUE TO PRIVACY CONCERNS**

**Comment by KanchanChauhan** [comment]
@creamdory Working on my local, had to migrate though. Field does not show since it does not have a value.

p

For duplicate, Sales Invoice did not have the trigger to recalculate, need to add that.

**Comment by creamdory** [comment]
Closing this PR since @KanchanChauhan is including this in her changes.

**Pull request closed without merging**
